name: Check Suite Completed

on:
  check_suite:
    types: [completed]

jobs:
  check-suite:
    runs-on: ubuntu-24.04

    steps:
      - run: echo '${{ toJSON(github.event) }}'

      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/workflows/check-suite-completed.js')
            await script({ github, context, core });
