name: Check Suite Completed

on:
  check_suite:
    types: [completed]
  workflow_run:
    types: [completed]
  workflow_dispatch:
    inputs:
      owner:
        description: The account owner of the repository. The name is not case sensitive.
        required: true
        type: string
      repo:
        description: The name of the repository without the .git extension. The name is not case sensitive.
        required: true
        type: string
      head_sha:
        description: The SHA of the commit.
        required: true
        type: string

jobs:
  check-suite:
    runs-on: ubuntu-24.04

    steps:
      - run: echo '${{ toJSON(github.event) }}'

      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github

      - uses: actions/github-script@v7
        env:
          OWNER: ${{ inputs.owner }}
          REPO: ${{ inputs.repo }}
          HEAD_SHA: ${{ inputs.head_sha }}
        with:
          script: |
            const script = require('./.github/workflows/check-suite-completed.js')
            await script({ github, context, core });
