name: Hello World

on:
  pull_request:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-24.04

    steps:
      - run: echo "Hello, World!"

      - run: echo "Test Github Step Summary" >> $GITHUB_STEP_SUMMARY

      - run: touch artifact.txt

      - name: Create empty file to upload artifact
        run: '> $RUNNER_TEMP/empty.txt'
        shell: bash

      # The maximum length is reported to be 260 characters. A full list of invalid artifact name characters is documented here:
      # https://github.com/actions/toolkit/blob/main/packages/artifact/src/internal/upload/path-and-artifact-name-validation.ts
      - uses: actions/upload-artifact@v4
        with:
          name: hello=true
          path: ${{ runner.temp }}/empty.txt
          if-no-files-found: error
          overwrite: true
