name: Hello World 2

on:
  pull_request:
    branches:
      - main

jobs:
  hello-world-2:
    runs-on: ubuntu-24.04

    steps:
      - run: echo "Hello, World 2!"

      - name: hello2
        uses: actions/github-script@v7
        with:
          script: |
            const { default: hello2 } =
              await import('${{ github.workspace }}/.github/workflows/src/hello2.js');
            await hello2({ github, context, core });
