name: Hello World

on:
  pull_request:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-24.04

    steps:
      - run: echo "Hello, World!"

      - run: echo "Test Github Step Summary" >> $GITHUB_STEP_SUMMARY
