name: Summary

on:
  check_suite:
    # Depends on check_run status, so must re-evaluate whenever a check_suite is completed.
    # Could instead trigger on check_run events, but I think this is unnecessarily noisy.
    types: [completed]
  pull_request:
    types:
      # Depends on labels, so must re-evaluate whenever a label is manually added or removed.
      - labeled
      - unlabeled
      # Depends on check_run status, so must re-evaluate whenever checks could be re-run
      - opened
      - edited
      - reopened
      - synchronize
  workflow_dispatch:
    inputs:
      owner:
        description: The account owner of the repository. The name is not case sensitive.
        required: true
        type: string
      repo:
        description: The name of the repository without the .git extension. The name is not case sensitive.
        required: true
        type: string
      issue_number:
        description: The number of the pull request.
        required: true
        type: string
      head_sha:
        description: The SHA of the commit.
        required: true
        type: string

jobs:
  summary:
    runs-on: ubuntu-24.04

    steps:
      - name: Log Event
        run: echo '${{ toJSON(github.event) }}'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github

      - name: Summary
        uses: actions/github-script@v7
        env:
          OWNER: ${{ inputs.owner }}
          REPO: ${{ inputs.repo }}
          ISSUE_NUMBER: ${{ inputs.issue_number }}
          HEAD_SHA: ${{ inputs.head_sha }}
        with:
          script: |
            const script = await import('${{ github.workspace }}/.github/workflows/src/summary.js')
            await script({ github, context, core });
